modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="hantai_no_tengoku"
version="1.0.0"
displayName="Hantai No Tengoku"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="kenzi, MCreator"

[[dependencies.hantai_no_tengoku]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.hantai_no_tengoku]]
    modId="geckolib"
    mandatory=false
    ordering="NONE"
    side="BOTH"

